site_name: Gradescope Autograder Documentation
repo_url: https://github.com/gradescope/autograder_samples
docs_dir: .
theme: readthedocs
extra_css: [gradescope.css]
pages:
- 'Home': index.md
- 'Getting Started': getting_started.md
- 'Autograder Specifications': specs.md
- 'Technical Details': tech.md
- 'Troubleshooting': troubleshooting.md
- 'Advanced Usage': advanced.md
- 'Leaderboards': leaderboard.md
- 'Examples':
    - 'Python': python/index.md
    - 'Java': java/index.md
    - 'Java+Maven': java-mvn/index.md
